name: User Login Unit Testing

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-user-login:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version your project requires

      # Step 3: Change to project directory
      - name: Change to project directory
        run: cd Scaffolding-Files # Ensure this matches the correct folder containing package.json

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 5: Run unit tests
      - name: Run User Login Unit Tests
        run: |
          npm test -- UserLoginController.test.js