name: Fix Web Context Load Error

on:
    workflow_dispatch:

jobs:
    fix-error:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: remove db folder
              run: |
                  if [ -d "db" ]; then
                      rm -rf db
                  fi

            - name: remove node_modules folder
              run: |
                  if [ -d "node_modules" ]; then
                      rm -rf node_modules
                  fi

            - name: remove package-lock.json
              run: |
                  if [ -f "package-lock.json" ]; then
                      rm package-lock.json
                  fi

            - name: install dependencies
              run: |
                  npm install express express-session

            - name: install Docker Compose
              run: |
                  sudo apt-get update
                  sudo apt-get install -y docker-compose
                  
            - name: stop and remove existing Docker containers
              run: |
                  docker-compose down

            - name: build and start Docker containers
              run: |
                  docker-compose up --build
