name: Fix Web Context Load Error

on:
    workflow_dispatch:

jobs:
    fix-error:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: remove db folder
              run: |
                  if [ -d "db" ]; then
                      rm -rf db
                  fi

            - name: remove node_modules folder
              run: |
                  if [ -d "node_modules" ]; then
                      rm -rf node_modules
                  fi

            - name: remove package-lock.json
              run: |
                  if [ -f "package-lock.json" ]; then
                      rm package-lock.json
                  fi

            - name: install Docker Compose
              run: |
                  sudo apt-get update
                  sudo apt-get install -y docker-compose

            - name: Create .env file from env-sample
              run: |
                  cp ${{ github.workspace }}/Scaffolding-Files/env-sample ${{ github.workspace }}/Scaffolding-Files/.env
                
            - name: install dependencies npm express
              run: |
                  npm install express

            - name: install dependencies npm express-session
              run: |
                  npm install express-session
                  
            - name: stop and remove existing Docker containers
              run: |
                  docker-compose -f ${{ github.workspace }}/Scaffolding-Files/docker-compose.yml --env-file ${{ github.workspace }}/Scaffolding-Files/.env down
